# Generated by Django 5.1.4 on 2025-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('capital_name', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=300)),
                ('religions', models.CharField(max_length=300)),
                ('telephone_code', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='static/uploads')),
            ],
        ),
    ]
