# Generated by Django 5.1.4 on 2025-01-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapi', '0002_countryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinationapi.countryname'),
        ),
    ]
