# Generated by Django 5.1.4 on 2025-01-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationapi', '0004_alter_country_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(blank=True, default=True, max_length=1000, null=True),
        ),
    ]
